/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 30-Apr-2019 17:55:51 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_boundaryFaceString CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_boundaryFaceString
(
	UID uuid NOT NULL,
	Name varchar(50) NOT NULL,
	Description varchar(255) NULL,
	LongDescription text NULL,
	ExtDescriptionURL varchar(255) NULL,
	locationByText text NULL,
	geometry geometry(LINESTRING,4326) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE i4ldata.t_boundaryFaceString ADD CONSTRAINT PK_t_boundaryFaceString
	PRIMARY KEY (UID)
;

CREATE INDEX spx_BoundaryFaceString ON i4ldata.t_boundaryFaceString using GIST(geometry)
;