/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 09-Okt-2018 15:17:08 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_AddSpatialSourceDocuments CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_AddSpatialSourceDocuments
(
	UID uuid NOT NULL,
	SpatialSourceUID uuid NULL,
	Type varchar(255) NOT NULL,
	Description varchar(255) NULL,
	ContentItem varchar(255) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE i4ldata.t_AddSpatialSourceDocuments ADD CONSTRAINT PK_t_AddSpatialSourceDocuments
	PRIMARY KEY (UID)
;

CREATE INDEX IXFK_t_AddSpatialSourceDocuments_t_SpatialSources ON i4ldata.t_AddSpatialSourceDocuments (SpatialSourceUID ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE i4ldata.t_AddSpatialSourceDocuments ADD CONSTRAINT FK_t_AddSpatialSourceDocuments_t_SpatialSources
	FOREIGN KEY (SpatialSourceUID) REFERENCES i4ldata.t_SpatialSources (UID) ON DELETE No Action ON UPDATE No Action
;
