/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 16-Sep-2018 23:02:58 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_ContentIndex CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_ContentIndex
(
	ContentUID uuid NOT NULL,
	ContentHashID varchar(50) NULL,
	ContentMimeType varchar(50) NOT NULL,
	ContentSize bigint NOT NULL,
	ContentName varchar(50) NULL,
	ContentDescription varchar(255) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE i4ldata.t_ContentIndex ADD CONSTRAINT PK_t_contentindex
	PRIMARY KEY (ContentUID)
;