/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 06-Sep-2018 14:36:04 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_itemLookUp CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_itemLookUp
(
	ID integer NOT NULL,
	ItemName varchar(50) NOT NULL,
	TableName varchar(50) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE i4ldata.t_itemLookUp ADD CONSTRAINT PK_t_itemLookUp
	PRIMARY KEY (ID)
;