/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 02-Okt-2018 00:28:46 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_Images CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_Images
(
	UID uuid NOT NULL,
	Name varchar(50) NOT NULL,
	Description varchar(50) NULL,
	MBR geometry(POLYGON,SRID) NULL,
	FlightDate timestamp NULL,
	Altitude numeric(10,2) NULL,
	Overlap integer NULL,
	Drone varchar(50) NULL,
	ContentItem varchar(50) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE i4ldata.t_Images ADD CONSTRAINT PK_t_Images
	PRIMARY KEY (UID)
;

CREATE INDEX spx_t_images ON i4ldata.t_Images (using GIST(mbr))
;