/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 16-Nov-2018 17:44:15 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_Processes CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_Processes
(
	UID uuid NOT NULL,
	ProjectUID uuid NOT NULL,
	CreatedBy varchar(50) NOT NULL,
	CreatedAt timestamp NOT NULL,
	LastModifiedBy varchar(50) NOT NULL,
	LastModifiedAt timestamp NOT NULL,
	Status varchar(32) NOT NULL,
	ToolName varchar(50) NOT NULL,
	ToolVersion varchar(50) NOT NULL,
	EntryPoint uuid NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE i4ldata.t_Processes ADD CONSTRAINT PK_t_process
	PRIMARY KEY (UID)
;
