/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 04-Okt-2018 13:24:15 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_Logs CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_Logs
(
	ProcessUID uuid NOT NULL,
	LogSeq integer NOT NULL,
	LogDate timestamp NOT NULL,
	LogSource varchar(50) NULL,
	LogLevel varchar(50) NOT NULL,
	LogText text NOT NULL
)
;