/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 30-Apr-2019 17:55:51 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_Projects CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_Projects
(
	UID uuid NOT NULL,
	Name varchar(50) NULL,
	Description varchar(255) NULL,
	LongDescription text NULL,
	ExtDescriptionURL varchar(255) NULL,
	ProjectDir varchar(255) NULL,
	AOI geometry(POLYGON,4326) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE i4ldata.t_Projects ADD CONSTRAINT PK_t_Project
	PRIMARY KEY (UID)
;

CREATE INDEX spx_t_projects ON i4ldata.t_Projects using GIST(AOI)
;