/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 09-Oct-2019 18:12:13 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_DDILayersImages CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_DDILayersImages
(
	UID uuid NOT NULL,
	DDILayerUID uuid NULL,
	ContentUID uuid NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE i4ldata.t_DDILayersImages ADD CONSTRAINT PK_t_DDILayersImages
	PRIMARY KEY (UID)
;

CREATE INDEX IXFK_t_DDILayersImages_t_DDILayers ON i4ldata.t_DDILayersImages (DDILayerUID ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE i4ldata.t_DDILayersImages ADD CONSTRAINT FK_t_DDILayersImages_t_DDILayers
	FOREIGN KEY (DDILayerUID) REFERENCES i4ldata.t_DDILayers (UID) ON DELETE Cascade ON UPDATE Cascade
;
