/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 31-Okt-2018 14:48:27 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_ProjectComputationResults CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_ProjectComputationResults
(
	ProjectUID uuid NOT NULL,
	ComputeDate timestamp NOT NULL,
	ProcessUID varchar(50) NULL,
	ResultType varchar(50) NULL,
	ResultUID uuid NULL
)
;