/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 28-Mai-2019 18:39:19 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_ImageSets CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_ImageSets
(
	UID uuid NOT NULL,
	Name varchar(50) NOT NULL,
	Description varchar(255) NULL,
	LongDescription text NULL,
	ExtDescriptionURL varchar(255) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE i4ldata.t_ImageSets ADD CONSTRAINT PK_t_ImageSets
	PRIMARY KEY (UID)
;