/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 17-Dec-2019 17:12:52 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_SpatialSources CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_SpatialSources
(
	UID uuid NOT NULL,
	Name varchar(255) NULL,
	Description varchar(255) NULL,
	LongDescription text NULL,
	ExtDescriptionURL varchar(255) NULL,
	Type varchar(255) NULL,
	ContentItem varchar(255) NULL,
	Measurements varchar(50) NULL,
	Procedure varchar(50) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE i4ldata.t_SpatialSources ADD CONSTRAINT PK_t_SpatialSource
	PRIMARY KEY (UID)
;