/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 06-Sep-2018 14:36:03 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_fsubtype CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_fsubtype
(
	fgroup varchar(50) NOT NULL,
	ftype varchar(50) NOT NULL,
	fsubtype varchar(50) NOT NULL,
	fgroupURI varchar(255) NULL,
	description text NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE i4ldata.t_fsubtype ADD CONSTRAINT PK_t_fsubtype
	PRIMARY KEY (fgroup,ftype,fsubtype)
;

CREATE INDEX IXFK_t_fsubtype_t_ftype ON i4ldata.t_fsubtype (fgroup ASC,ftype ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE i4ldata.t_fsubtype ADD CONSTRAINT FK_t_fsubtype_t_ftype
	FOREIGN KEY (fgroup,ftype) REFERENCES i4ldata.t_ftype (fgroup,ftype) ON DELETE No Action ON UPDATE No Action
;