/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 30-Jan-2019 12:44:00 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_EntryPoint CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_EntryPoint
(
	UID uuid NOT NULL,
	ToolImageUID uuid NOT NULL,
	Name varchar(50) NOT NULL,
	Description varchar(255) NULL,
	LongDescription text NULL,
	EntryPoint varchar(255) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE i4ldata.t_EntryPoint ADD CONSTRAINT PK_t_SubTools
	PRIMARY KEY (UID)
;

CREATE INDEX IXFK_t_EntryPoint_t_ToolImages ON i4ldata.t_EntryPoint (ToolImageUID ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE i4ldata.t_EntryPoint ADD CONSTRAINT FK_t_EntryPoint_t_ToolImages
	FOREIGN KEY (ToolImageUID) REFERENCES i4ldata.t_ToolImages (UID) ON DELETE Cascade ON UPDATE Cascade
;