/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 28-Jan-2019 20:06:51 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_Classifier CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_Classifier
(
	UID uuid NOT NULL,
	Name varchar(50) NULL,
	Description text NULL,
	ClassifierType varchar(50) NULL,
	ContentItem varchar(255) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE i4ldata.t_Classifier ADD CONSTRAINT PK_t_Classifier
	PRIMARY KEY (UID)
;