/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 06-Sep-2018 14:36:03 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_fgroup CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_fgroup
(
	fgroup varchar(50) NOT NULL,
	fgroupURI varchar(255) NULL,
	description text NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE i4ldata.t_fgroup ADD CONSTRAINT PK_t_group
	PRIMARY KEY (fgroup)
;