/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 30-Jan-2019 12:44:00 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_Tools CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_Tools
(
	UID uuid NOT NULL,
	Name varchar(255) NOT NULL,
	Description varchar(255) NULL,
	LongDescription text NULL,
	ExtDescriptionURL varchar(255) NULL,
	Supplier varchar(50) NULL,
	ToolURL varchar(255) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE i4ldata.t_Tools ADD CONSTRAINT PK_t_Tools
	PRIMARY KEY (UID)
;