/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 04-Okt-2018 12:14:00 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_ProcessParameters CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_ProcessParameters
(
	ProcessUID uuid NOT NULL,
	ParameterName varchar(50) NOT NULL,
	ParameterValue varchar(255) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

CREATE INDEX IXFK_t_ProcessParameters_t_Process ON i4ldata.t_ProcessParameters (ProcessUID ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE i4ldata.t_ProcessParameters ADD CONSTRAINT FK_t_ProcessParameters_t_Process
	FOREIGN KEY (ProcessUID) REFERENCES i4ldata.t_Processes (UID) ON DELETE Cascade ON UPDATE Cascade
;