/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 28-Sep-2018 16:16:16 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_Models CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_Models
(
	UID uuid NOT NULL,
	Name varchar(50) NULL,
	Description varchar(255) NULL,
	Trainingset uuid NULL,
	Classifier uuid NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE i4ldata.t_Models ADD CONSTRAINT PK_t_Model
	PRIMARY KEY (UID)
;