/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 06-Sep-2018 14:36:04 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_Tags CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_Tags
(
	UID uuid NOT NULL,
	Tags varchar(50) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE i4ldata.t_Tags ADD CONSTRAINT PK_t_Tags
	PRIMARY KEY (UID)
;

ALTER TABLE i4ldata.t_Tags ADD CONSTRAINT idx_uq_tag UNIQUE (Tags)
;