/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 24-Oct-2019 17:11:44 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_AdminSource CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_AdminSource
(
	UID uuid NOT NULL,
	Name varchar(50) NOT NULL,
	Description varchar(255) NULL,
	LongDescription text NULL,
	ExtDescriptionURL varchar(255) NULL,
	AdminSourceType varchar(50) NULL,
	ContentItem uuid NOT NULL,
	Concept uuid NULL,
	AvailabilityStatus varchar(50) NULL,
	purchasePrice numeric(12,2) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE i4ldata.t_AdminSource ADD CONSTRAINT PK_t_AdminSource
	PRIMARY KEY (UID)
;
