/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 06-Sep-2018 14:36:04 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_ftype CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_ftype
(
	fgroup varchar(50) NOT NULL,
	ftype varchar(50) NOT NULL,
	fgroupURI varchar(255) NULL,
	description text NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE i4ldata.t_ftype ADD CONSTRAINT PK_t_ftype
	PRIMARY KEY (fgroup,ftype)
;

CREATE INDEX IXFK_t_ftype_t_fgroup ON i4ldata.t_ftype (fgroup ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE i4ldata.t_ftype ADD CONSTRAINT FK_t_ftype_t_fgroup
	FOREIGN KEY (fgroup) REFERENCES i4ldata.t_fgroup (fgroup) ON DELETE No Action ON UPDATE No Action
;