/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 06-Sep-2018 14:36:04 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS i4ldata.t_Item2Item CASCADE
;

/* Create Tables */

CREATE TABLE i4ldata.t_Item2Item
(
	FromUID uuid NOT NULL,
	FromType varchar(50) NOT NULL,
	ToUID uuid NOT NULL,
	ToType varchar(50) NOT NULL,
	RelationType varchar(50) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE i4ldata.t_Item2Item ADD CONSTRAINT PK_t_Item2Item
	PRIMARY KEY (FromUID,FromType,ToUID,ToType)
;